name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: jiro4989/setup-nim-action@v1.0.2
    - uses: actions/checkout@v2
      with:
        nim-version: '1.0.6'
    - name: Run Tests
      run: |
        cd $GITHUB_WORKSPACE
        sh scripts/test.sh
